FROM python:3.11-slim

# Instalar dependencias del sistema (PDFs)
RUN apt-get update && apt-get install -y \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY requirements.txt .

# Instalar dependencias Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código
COPY . .

# Cloud Run usa esta variable
ENV PORT=8080

# Exponer el puerto
EXPOSE 8080

# Arranque en producción
CMD ["gunicorn", "-b", "0.0.0.0:8080", "main:app"]
